import {
  Container,
  Content,
  Title,
  Description,
  CheckCodeLink,
  NotionLogo,
} from './styles';

export function Home() {
  return (
    <Container>
      <Content>
        <NotionLogo />

        <Title>This is a blog generated by Notion</Title>

        <Description>
          use your notion as an admin page to create and manage posts
        </Description>

        <CheckCodeLink
          to="https://github.com/felipinas/notion-blog"
          target="_blank"
        >
          check the code
        </CheckCodeLink>
      </Content>
    </Container>
  );
}
